### ISSUE TITLE
Messages shouldn't be sent from the Database-module

### ISSUE THREAD

**Issue by lessp** [chas-academy/drmayday#8]
I've already began this work on a few places, but I feel there could be a better separation of concerns. The database-module should IMO only return the data (as a promise), not be responsible for sending the appropriate message.

See: https://github.com/chas-academy/drmayday/blob/master/src/adapters/Database.re#L251 as an example.

**Comment by joakimunge** [comment]
Yes, this is a good point and I found it confusing why for instance "getOpenItems" had so much more responsibility than others.

I'm currently writing a new Database action and I will follow the convention you mentioned

**Comment by lessp** [comment]
Cool! Feel free to to refactor the old ones as well!
